export const asyncRouterMap =[
    {
        path:'/home',
        name:"Home",
        meta:{title:"首页",role:['admin','teacher','manager'],icon:'DesktopOutlined'},
    },
    {
        path:'/personal',
        name:"Personal",
        meta:{title:"个人中心",role:['admin','teacher','manager'],icon:'DesktopOutlined'},
    },
    {
        path:'/teacher',
        name:"Teacher",
        meta:{title:"教师管理",role:['admin',],icon:'DesktopOutlined'},
    },
    {
        path:'/admissions',
        name:"Admissions",
        meta:{title:"招生管理",role:['admin','manager'],icon:'DesktopOutlined'},
        children:[
            {
                path:'/admissions/intentional',
                name:'Intentional',
                meta:{title:"意向学员管理",role:['admin','manager'],icon:'DesktopOutlined'},
            },
            {
                path:'/admissions/check',
                name:'check',
                meta:{title:"邀约查询",role:['admin','manager'],icon:'DesktopOutlined'},
            }
        ]
    },
    {
        path:'/student',
        name:"Student",
        meta:{title:"学生管理",role:['admin','teacher','manager'],icon:'DesktopOutlined'},
        children:[
            {
                path:'/student/info',
                name:'Info',
                meta:{title:"学生管理",role:['admin','manager'],icon:'DesktopOutlined'},
            },
            {
                path:'/student/exam',
                name:'Exam',
                meta:{title:"考试管理",role:['admin','manager'],icon:'DesktopOutlined'},
            }
        ]
    },
    {
        path:'/courseSchedulingManagement',
        name:"CourseSchedulingManagement",
        meta:{title:"排课管理",role:['admin','manager'],icon:'DesktopOutlined'}
    },
    {
        path:'/administration',
        name:"Administration",
        meta:{title:"行政管理",role:['admin','manager'],icon:'DesktopOutlined'}
    },
    {
        path:'/finance',
        name:"Finance",
        meta:{title:"财务管理",role:['admin'],icon:'DesktopOutlined'}
    }
]